<a href="https://colab.research.google.com/github/szandian/test/blob/main/machinlearning_H_A_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from matplotlib import pyplot as plt


creat array, matrix


In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

shape:
show matrix size

In [ ]:
print(a.shape,b.shape)

(4,) (2, 2)


# **reshape**:size change or add new dimention to variable
list_name.reshape(new_size)


In [ ]:
c = a.reshape((4,1))
c


array([[1],
       [2],
       [3],
       [4]])

In [ ]:
c.shape

(4, 1)

in the below exapmle:The multiplication of numbers must be equal to the number of elements of the matrix
if we don't know about the number of elements we can put (-1)in second place(middle one). it automatically correct the shape of matrix

In [ ]:
d=a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [ ]:
d=a.reshape((2,-1,1))
d.shape

(2, 2, 1)

**concatinate** two lists:
np.cancatinate(l1,l2)


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6,])
c = a + b
c

array([5, 7, 9])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6,])
c = a * b
c

array([ 4, 10, 18])

In [ ]:
c = np.array([10])
d= a + c
d

array([11, 12, 13])

Arrays with Different Shapes (**Broadcasting**):
Broadcasting allows you to perform operations on arrays with different shapes, as long as they are compatible. NumPy automatically broadcasts the smaller array to match the shape of the larger array.

In [ ]:
e = a + 5
e

array([6, 7, 8])

In [ ]:
a = np.array([1,2,3,4,5,6,9,8,])
a.shape

(8,)

**slice:**

In [ ]:
b = a[2:7]
b

array([3, 4, 5, 6, 9])

**step length**


In [ ]:
b = a [2:7:2]
b

array([3, 5, 9])

In [ ]:
c = a[a>3]
c

array([4, 5, 6, 9, 8])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 9, 8])

Calculate the sum of all elements of the vector
np.sum(list)

In [ ]:
sum_a = np.sum(a)
sum_a

38

In [ ]:
max_a = np.max(a)
max_a

9

In [ ]:
min_a = np.min(a)
min_a

1

np.sort(list):
sort min to max



In [ ]:
a = np.array([4,10,0,5,8,3,7,1,6])
b = np.sort(a)
b

array([ 0,  1,  3,  4,  5,  6,  7,  8, 10])

build a random matrix with integer number, between 0-10 with 3*4 size



In [ ]:
a = np.random.randint(0,10,(3,4))

In [ ]:
a = np.random.randint(-100,100,(3,5))
a

array([[ 17,  27,   8,  -8,  58],
       [-74, -71,  93,  26, -14],
       [  8,  -7, -71, -39, -44]])

put some lists together vertically:
np.vstack((list1,list2))
a,b must be as topple, means put them in ()

> Indented block



In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c.shape

(2, 3)

put some lists together horizontally: it is similar to cancatinating
np.hstack((list1,list2))

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

normalize:

data normalization: mean list and standard (miangin va enheraf az meyar ra bayad hesab kard)
np.mean(list)
np.std(list)


In [ ]:
mean_a = np.mean(a)
mean_a

2.0

Standard Deviation:

The standard deviation measures how spread out or dispersed the values in a set are from the mean.
A low standard deviation indicates that the values are close to the mean, while a high standard deviation indicates that the values are more spread out.
It provides a way to understand the variability or "wiggle room" in the data.
Example:

Consider two sets of numbers: Set A: 2, 4, 6, 8, 10 and Set B: 3, 3, 6, 9, 12.
Both sets have the same mean (6), but Set B has a higher standard deviation because its values are more spread out from the mean.
So, the standard deviation helps us understand how much individual values in a set deviate from the average.

In [ ]:
std_a = np.std(a)
std_a

0.816496580927726

In [ ]:
norm_a = (a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [ ]:
np.mean(norm_a)

0.0

In [ ]:
np.std(norm_a)

0.9999999999999999

normalize kardan yani miangeen ra be samt 0 va enheraf meyar ra be samt 1 meyl dahim


In [ ]:
import pandas as pd


create:  craete a data frame (table)

pd.DataFrame()

In [ ]:
data = {
    "Name":["a","b","c"],
    "Age":[28,25,30]
}
df = pd.DataFrame(data)

read files:

pd.read_csv
suffix csv is for exell files

first rows are the name of coulomns.
There should be no spaces between lines

In [ ]:

df=pd.read_csv("/content/data.txt")
df


Name  Age  Salary
0   Hasan   32    1000
1     Ali   33    4000
2    reza   51    6000
3  maryam   45    2000
4   zahra   25    3500
5    lili   28    3000
6    fati   36    5000
7    titi   37    7000

dataframe_name.head()
 ساختار کلی جدول مورد استفاده و 5 سطر اول آن را به ما نشان می دهد.

In [ ]:
df.head()

Name  Age  Salary 
0   Hasan   32     1000
1     Ali   33     4000
2    reza   51     6000
3  maryam   45     2000
4   zahra   25     3500


to show a definite column:
df["column_name"]





In [ ]:
df['Salary']

0    1000
1    4000
2    6000
3    2000
4    3500
5    3000
6    5000
7    7000
Name: Salary, dtype: int64

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Salary '], dtype='object')


df.iloc[idx.:]
اطلاعات مربوط به سطر با شماره اندیس idx را نشان خواهد داد

> Indented block



In [ ]:
df.iloc[5]

Name       lili
Age          28
Salary     3000
Name: 5, dtype: object

describe
اطلاعات کلی آماری از جمله میانگین و مینیمم و ماکزیمم جدول را محاسبه می کند.

In [ ]:
df.describe()

Age       Salary
count   8.000000     8.000000
mean   35.875000  3937.500000
std     8.592979  2007.797301
min    25.000000  1000.000000
25%    31.000000  2750.000000
50%    34.500000  3750.000000
75%    39.000000  5250.000000
max    51.000000  7000.000000

In [ ]:
df['Salary']

0    1000
1    4000
2    6000
3    2000
4    3500
5    3000
6    5000
7    7000
Name: Salary, dtype: int64

In [ ]:
df.iloc[2,:]

Name      reza
Age         51
Salary    6000
Name: 2, dtype: object

In [ ]:
df.iloc[4,1]

25

In [ ]:
df.iloc[4,2]

3500

Filtee

In [ ]:
filtered_df=df[df["Salary"]>2500]
filtered_df

Name  Age  Salary
1    Ali   33    4000
2   reza   51    6000
4  zahra   25    3500
5   lili   28    3000
6   fati   36    5000
7   titi   37    7000

In [ ]:
filtered_df=df[df["Salary"]>5000]
filtered_df

Name  Age  Salary
2  reza   51    6000
7  titi   37    7000

Sort_value
به ما کمک می کند تا اطلاعات را با توجه به ستون مشخص شده مرتب کنیم

In [ ]:
df_sorted=df.sort_values("Salary")
df_sorted

Name  Age  Salary
0   Hasan   32    1000
3  maryam   45    2000
5    lili   28    3000
4   zahra   25    3500
1     Ali   33    4000
6    fati   36    5000
2    reza   51    6000
7    titi   37    7000